version: '3.3'

services:
  rp-db:
    image: container-registry.oracle.com/mysql/community-server:8.4
    container_name: rp-db
    restart: always
    #env_file: .env
    environment:
      - MYSQL_DATABASE=zwroty_e_strix_com
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - ./mysql-dump/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      rp-network:
        aliases:
          - db.rp.e-strix.pl
  rp-mock:
    image: estrix/tomcat-mock
    container_name: rp-mock
    build: ./docker/tomcat
    environment:
      - DEBUG_APP=true
      - TOMCAT_USER=root
      - TOMCAT_PASSWORD=password
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - ./logs/server/:/opt/tomcat/logs/
      - ./data/server/:/opt/data/
    networks:
      rp-network:
        aliases:
          - rp.e-strix.pl
  parcel-server:
    image: "registry.hub.docker.com/kamilmucik/return-parcel-server:2.6.0"
    container_name: parcel-server
    #   platform: linux/x86_64
    platform: linux/amd64
    volumes:
      - ./config/server/artifacts/tomcat/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./config/server/artifacts/tomcat/conf/custom.properties:/usr/local/tomcat/conf/custom.properties
      - ./logs/server/:/opt/tomcat/logs/
    environment:
      DEBUG_APP: 'true'
    ports:
      - 8000:8000
      - 8881:8080
      - 9100:9100
    networks:
      rp-network:

volumes:
  rp-dbdata8_0_25:

networks:
  rp-network:
    driver: bridge
