<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>pl.estrix</groupId>
    <artifactId>return-parcel</artifactId>
    <version>2.5.5</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>

        <jmeterScript>test_proof_001.jmx</jmeterScript>
        <scenario.max.threads>30</scenario.max.threads>
        <scenario.duration>600</scenario.duration>
        <scenario.ramp.up.period>300</scenario.ramp.up.period>
        <records.number.in.request>50</records.number.in.request>
    </properties>

    <dependencies>
    </dependencies>

    <profiles>
        <profile>
            <id>local-docker</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <var.d3s.protocol>http</var.d3s.protocol>
                <var.d3s.url>127.0.0.1</var.d3s.url>
                <var.d3s.port>8080</var.d3s.port>
            </properties>
        </profile>
        <profile>
            <id>QA</id>
            <properties>
                <var.d3s.protocol>http</var.d3s.protocol>
                <var.d3s.url>rp.e-strix.pl</var.d3s.url>
                <var.d3s.port>80</var.d3s.port>
            </properties>
        </profile>
        <profile>
            <id>FindByEAN</id>
            <properties>
                <jmeterScript>PerfTestScenario-FindByEAN.jmx</jmeterScript>
                <scenario.max.threads>10</scenario.max.threads>
                <scenario.duration>3600</scenario.duration>
                <scenario.ramp.up.period>300</scenario.ramp.up.period>
            </properties>
        </profile>
        <profile>
            <id>UploadImage</id>
            <properties>
                <jmeterScript>PerfTestScenario-UploadImage.jmx</jmeterScript>
                <scenario.max.threads>15</scenario.max.threads>
                <scenario.duration>600</scenario.duration>
                <scenario.ramp.up.period>300</scenario.ramp.up.period>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>com.lazerycode.jmeter</groupId>
                <artifactId>jmeter-maven-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <id>configuration</id>
                        <goals>
                            <goal>configure</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jmeter-tests</id>
                        <goals>
                            <goal>jmeter</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jmeter-tests2</id>
                        <goals>
                            <goal>results</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jmeterExtensions>
                        <jmeterExtension>kg.apc:jmeter-plugins-perfmon:2.1</jmeterExtension>
                    </jmeterExtensions>
                    <testFilesIncluded>
                        <jMeterTestFile>${jmeterScript}</jMeterTestFile>
                    </testFilesIncluded>
                    <propertiesUser>
                        <var.d3s.protocol>${var.d3s.protocol}</var.d3s.protocol>
                        <var.d3s.url>${var.d3s.url}</var.d3s.url>
                        <var.d3s.port>${var.d3s.port}</var.d3s.port>
                        <scenario.max.threads>${scenario.max.threads}</scenario.max.threads>
                        <scenario.duration>${scenario.duration}</scenario.duration>
                        <scenario.ramp.up.period>${scenario.ramp.up.period}</scenario.ramp.up.period>
                    </propertiesUser>
                    <jMeterProcessJVMSettings>
                        <xms>3072</xms>
                        <xmx>3072</xmx>
<!--                        <arguments>-->
<!--                            <argument>-Djavax.net.ssl.keyStore=${basedir}/src/test/resources/${var.d3s.keyStore}</argument>-->
<!--                            <argument>-Djavax.net.ssl.keyStorePassword=${var.d3s.keyStorePass}</argument>-->
<!--                            <argument>-Djavax.net.ssl.keyStoreType=pkcs12</argument>-->
<!--                        </arguments>-->
                    </jMeterProcessJVMSettings>
                    <generateReports>true</generateReports>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
