server:
  port: 8004

logging:
  level:
    pl.estrix.zwroty: DEBUG

spring:
  application:
    name: textextractor-service

textextractor-service:
  aws-access-key-id: "${AWS_ACCESS_KEY}"
  aws-secret-access-key: "${AWS_SECRET_KEY}"
  gcp-access-key-id: "${GCP_ACCESS_KEY}"
  gcp-secret-access-key: "${GCP_SECRET_KEY}"
